In [110]:
import numpy as np
import pandas as pd
import uproot as up 
import os
import matplotlib
#matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as mcolors
from matplotlib.path import Path
from matplotlib.collections import LineCollection
from matplotlib.ticker import MultipleLocator
from datetime import datetime

working_dir = os.getcwd()
print(working_dir)
date = datetime.now().strftime("%Y-%m-%d")
print(date)

%load_ext autoreload
%autoreload 2

import my_functions_in_coi as fct_in
import my_functions as fct

/Users/antoinevezon/bruit_de_fond/Analyse
2026-01-16
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [111]:
Adc_to_mV = 0.29175
Qt2t_to_pC = 0.16699
 
on_lab_desktop = False
on_my_laptop = not on_lab_desktop

#saving fig path
if on_lab_desktop == True:
    save_dir_path = "/home/vezon/bruit_de_fond"
if on_my_laptop == True:
    save_dir_path = "/Users/antoinevezon/Desktop/"


### LECTURE DU DATATREE ###                                                                            |Corresponding names manually created with mon_group2tree_v3       

rootfile_name_a = "Test_GADGET_GorG2orG4orG24_0001.root"         # 500mbar                             |GorG2orG4orG24.root" 500 mbar
rootfile_name_b = "Test_GADGET_GorG2orG4orG24_V2_0001.root"      # 500mbar                             |GorG2orG4orG24_V2.root" 500 mbar
rootfile_name_c = "Test_GADGET_1bar_GorG2orG4orG24_0001.root"    #                                     |1bar_GorG2orG4orG24.root
rootfile_name_d = "Test_GADGET_1.5bar_GorG2orG4orG24_0001.root"  #                                     |1.5bar_GorG2orG4orG24.root

rootfile_name_e = "New_plastics_2000V_atleast_GADGET_withblackcover_500mbar_0001.root"  # \            |New_plastics_atleastGAD_500mbar.root
rootfile_name_f = "New_plastics_2500V_atleast_GADGET_withblackcover_1000mbar_0001.root" #  |           |New_plastics_atleastGAD_1000mbar.root
rootfile_name_g = "New_plastics_2500V_atleast_GADGET_withblackcover_ascension_0001.root"# /¦ 1500mbar  |New_plastics_atleastGAD_1500mbar.root
rootfile_name_h = "New_plastics_2000V_atleastGAD_Empty_0001.root"#                         ¦           |New_plastics_atleastGAD_Empty.root 
rootfile_name_i = "New_plastics_atleastGAD_Empty_V2_0001.root"   #                         ¦           |New_plastics_atleastGAD_Empty_V2.root
#                                                                                          v  
#                                                            QDC_2 & QDC_4 = resp. Right & Left_pastic ! 
#                                                            Donc il faut les échanger pour etre identique aux Empty   
rootfile_name_j = "AtleastGAD_woplastics_500mbar_0001.root"
rootfile_name_k = "AtleastGAD_woplastics_500mbar_no_blancket_test_0001.root"
rootfile_name_l = "AtleastGAD_woplastics_500mbar_no_blancket_test_before-after-0ns_0001.root"

rootfile_name_m = "0007992__cycle147.root"

##################################
rootfile_use = rootfile_name_m
##################################

if on_lab_desktop == True:
    path_to_DataTree_faster2root = f"/home/vezon/bruit_de_fond/data/root/faster2root/{rootfile_use}:DataTree;1"
    path_to_DataTree_group2tree_v3 = f"/home/vezon/bruit_de_fond/data/root/group2tree_v3/{rootfile_use}:DataTree;1"

if on_my_laptop == True:
    path_to_DataTree_faster2root = f"/Users/antoinevezon/bruit_de_fond/data/root/faster2root/{rootfile_use}:DataTree;1"
    path_to_DataTree_group2tree_v3 = f"/Users/antoinevezon/bruit_de_fond/data/root/group2tree_v3/{rootfile_use}:DataTree;1"



DataTree_faster2root = up.open(path_to_DataTree_faster2root)


DataTree_faster2root.show()


Keys_f2r = DataTree_faster2root.keys()


print(f"\nKeys_f2r = {Keys_f2r}\n")


df = DataTree_faster2root.arrays(Keys_f2r, library="pd")

name                 | typename                 | interpretation
---------------------+--------------------------+-------------------------------
group_data_nb        | int64_t                  | AsDtype('>i8')
group_size           | int32_t                  | AsDtype('>i4')
group_time           | int64_t                  | AsDtype('>i8')
sub_num              | int32_t                  | AsDtype('>i4')
sub_time             | double                   | AsDtype('>f8')
sub_type             | char*                    | AsStrings()
sub_channel          | int32_t                  | AsDtype('>i4')
sub_Q                | int32_t                  | AsDtype('>i4')
sub_width            | int32_t                  | AsDtype('>i4')
sub_max_amp          | int32_t                  | AsDtype('>i4')
sub_max_pos          | int32_t                  | AsDtype('>i4')
sub_baseline         | int32_t                  | AsDtype('>i4')
sub_sat              | bool                     | AsDtype('bool')
sub_q1               | int32_t                  | AsDtype('>i4')
sub_q1_sat           | bool                     | AsDtype('bool')
sub_q2               | int32_t                  | AsDtype('>i4')
sub_q2_sat           | bool                     | AsDtype('bool')

Keys_f2r = ['group_data_nb', 'group_size', 'group_time', 'sub_num', 'sub_time', 'sub_type', 'sub_channel', 'sub_Q', 'sub_width', 'sub_max_amp', 'sub_max_pos', 'sub_baseline', 'sub_sat', 'sub_q1', 'sub_q1_sat', 'sub_q2', 'sub_q2_sat']

In [112]:
df.head(50)

,group_data_nb,group_size,group_time,sub_num,sub_time,sub_type,sub_channel,sub_Q,sub_width,sub_max_amp,sub_max_pos,sub_baseline,sub_sat,sub_q1,sub_q1_sat,sub_q2,sub_q2_sat
0,0,92,58495723952418,1,0.0,QT2T,11,193,8,39,2,20,False,-999999,False,-999999,False
1,0,92,58495723952418,2,4.0,QT2T,10,56,4,16,2,15,False,-999999,False,-999999,False
2,0,92,58495723952418,3,6.0,QT2T,9,123,9,17,2,19,False,-999999,False,-999999,False
3,1,92,58495795198820,1,0.0,QT2T,1,263,9,47,3,0,False,-999999,False,-999999,False
4,1,92,58495795198820,2,4.0,QT2T,2,144,7,28,3,5,False,-999999,False,-999999,False
5,1,92,58495795198820,3,16.0,QT2T,3,859,15,122,4,-20,False,-999999,False,-999999,False
6,2,92,58495837196318,1,0.0,QT2T,13,5676,27,849,4,4,False,-999999,False,-999999,False
7,2,92,58495837196318,2,2.0,QT2T,15,255,9,48,3,11,False,-999999,False,-999999,False
8,2,92,58495837196318,3,14.0,QT2T,14,82,5,20,2,11,False,-999999,False,-999999,False
9,3,92,58496053429288,1,0.0,QT2T,11,452,14,55,7,16,False,-999999,False,-999999,False
10,3,92,58496053429288,2,2.0,QT2T,10,169,10,26,6,3,False,-999999,False,-999999,False
11,3,92,58496053429288,3,8.0,QT2T,9,35,3,12,2,11,False,-999999,False,-999999,False
12,4,92,58496248540030,1,0.0,QT2T,1,323,9,61,3,-23,False,-999999,False,-999999,False
13,4,92,58496248540030,2,4.0,QT2T,2,398,18,40,3,26,False,-999999,False,-999999,False
14,4,92,58496248540030,3,18.0,QT2T,3,206,8,40,2,7,False,-999999,False,-999999,False
15,5,92,58496262252556,1,0.0,QT2T,5,78,5,20,2,-21,False,-999999,False,-999999,False
16,5,92,58496262252556,2,0.0,QT2T,6,117,6,26,2,-12,False,-999999,False,-999999,False
17,5,92,58496262252556,3,6.0,QT2T,7,349,9,67,3,5,False,-999999,False,-999999,False
18,6,92,58496537717280,1,0.0,QT2T,11,3919,22,605,4,-30,False,-999999,False,-999999,False
19,6,92,58496537717280,2,6.0,QT2T,9,135,6,30,2,4,False,-999999,False,-999999,False
20,6,92,58496537717280,3,6.0,QT2T,10,153,7,32,3,18,False,-999999,False,-999999,False
21,7,92,58496539511158,1,0.0,QT2T,13,89,5,22,2,-15,False,-999999,False,-999999,False
22,7,92,58496539511158,2,0.0,QT2T,14,80,5,19,2,-26,False,-999999,False,-999999,False
23,7,92,58496539511158,3,0.0,QT2T,15,364,17,37,10,44,False,-999999,False,-999999,False
24,8,92,58496540412290,1,0.0,QT2T,15,2014,17,300,4,-12,False,-999999,False,-999999,False
25,8,92,58496540412290,2,6.0,QT2T,13,120,6,26,2,10,False,-999999,False,-999999,False
26,8,92,58496540412290,3,8.0,QT2T,14,78,6,16,2,15,False,-999999,False,-999999,False
27,9,92,58496542231524,1,0.0,QT2T,11,6714,29,995,3,14,False,-999999,False,-999999,False
28,9,92,58496542231524,2,6.0,QT2T,9,347,12,53,6,4,False,-999999,False,-999999,False
29,9,92,58496542231524,3,6.0,QT2T,10,455,13,53,6,-4,False,-999999,False,-999999,False
30,10,92,58496544393914,1,0.0,QT2T,1,1290,20,144,4,32,False,-999999,False,-999999,False
31,10,92,58496544393914,2,2.0,QT2T,2,5092,31,641,4,-12,False,-999999,False,-999999,False
32,10,92,58496544393914,3,16.0,QT2T,3,3518,27,402,5,11,False,-999999,False,-999999,False
33,11,92,58496544911288,1,0.0,QT2T,11,425,12,70,3,18,False,-999999,False,-999999,False
34,11,92,58496544911288,2,2.0,QT2T,9,670,14,104,4,32,False,-999999,False,-999999,False
35,11,92,58496544911288,3,6.0,QT2T,10,377,9,64,2,-45,False,-999999,False,-999999,False
36,12,92,58496546720592,1,0.0,QT2T,11,604,16,68,8,-7,False,-999999,False,-999999,False
37,12,92,58496546720592,2,2.0,QT2T,9,1326,23,147,4,-5,False,-999999,False,-999999,False
38,12,92,58496546720592,3,4.0,QT2T,10,416,13,48,7,37,False,-999999,False,-999999,False
39,13,92,58496548918582,1,0.0,QT2T,1,260,11,39,2,-15,False,-999999,False,-999999,False
40,13,92,58496548918582,2,2.0,QT2T,2,404,14,45,7,2,False,-999999,False,-999999,False
41,13,92,58496548918582,3,16.0,QT2T,3,595,13,93,3,-7,False,-999999,False,-999999,False
42,14,92,58496551757364,1,0.0,QT2T,1,3328,23,425,5,2,False,-999999,False,-999999,False
43,14,92,58496551757364,2,2.0,QT2T,2,3533,26,455,4,36,False,-999999,False,-999999,False
44,14,92,58496551757364,3,16.0,QT2T,3,6068,28,780,4,9,False,-999999,False,-999999,False
45,15,92,58496553110686,1,0.0,QT2T,5,2228,19,336,4,-20,False,-999999,False,-999999,False
46,15,92,58496553110686,2,2.0,QT2T,6,557,14,73,5,-5,False,-999999,False,-999999,False
47,15,92,58496553110686,3,14.0,QT2T,7,248,8,49,2,14,False,-999999,False,-999999,False
48,16,92,58496553401162,1,0.0,QT2T,11,188,10,25,3,7,False,-999999,False,-999999,False
49,16,92,58496553401162,2,6.0,QT2T,10,53,4,15,2,5,False,-999999,False,-999999,False

In [113]:
#df.groupby('group_time')['sub_channel'].unique()

In [114]:
#ch_pop_in_grp = df.groupby('group_time')['sub_channel'].mean()
print(ch_pop_in_grp)

group_time
58495723952418    10.00
58495795198820     2.00
58495837196318    14.00
58496053429288    10.00
58496248540030     2.00
                  ...
99978669094876     1.75
99978876872936    10.00
99978962612506     9.75
99979349419924    14.00
99979428563268     2.00
Name: sub_channel, Length: 493624, dtype: float64

In [115]:
def set_detectors_channels(df, ch_RED = [1,2,3], ch_BLUE = [5,6,7], ch_YELLOW = [9,10,11], ch_WHITE = [12,13,14]):
    a=ch_RED[0]
    b=ch_RED[1]
    c=ch_RED[2]
    df_RED = df.query("sub_channel == @ch_RED[0] | sub_channel == @b | sub_channel == @c")
    a=ch_BLUE[0]
    b=ch_BLUE[1]
    c=ch_BLUE[2]
    df_BLUE = df.query("sub_channel == @a | sub_channel == @b | sub_channel == @c")
    a=ch_YELLOW[0]
    b=ch_YELLOW[1]
    c=ch_YELLOW[2]
    df_YELLOW = df.query("sub_channel == @a | sub_channel == @b | sub_channel == @c")
    a=ch_WHITE[0]
    b=ch_WHITE[1]
    c=ch_WHITE[2]
    df_WHITE = df.query("sub_channel == @a | sub_channel == @b | sub_channel == @c")
    
    return(df_RED,df_BLUE,df_YELLOW,df_WHITE)

In [116]:
df_RED,df_BLUE,df_YELLOW,df_WHITE = set_detectors_channels(df, ch_RED = [1,2,3], ch_BLUE = [5,6,7], ch_YELLOW = [9,10,11], ch_WHITE = [12,13,14])

In [117]:
df_RED

,group_data_nb,group_size,group_time,sub_num,sub_time,sub_type,sub_channel,sub_Q,sub_width,sub_max_amp,sub_max_pos,sub_baseline,sub_sat,sub_q1,sub_q1_sat,sub_q2,sub_q2_sat
3,1,92,58495795198820,1,0.0,QT2T,1,263,9,47,3,0,False,-999999,False,-999999,False
4,1,92,58495795198820,2,4.0,QT2T,2,144,7,28,3,5,False,-999999,False,-999999,False
5,1,92,58495795198820,3,16.0,QT2T,3,859,15,122,4,-20,False,-999999,False,-999999,False
12,4,92,58496248540030,1,0.0,QT2T,1,323,9,61,3,-23,False,-999999,False,-999999,False
13,4,92,58496248540030,2,4.0,QT2T,2,398,18,40,3,26,False,-999999,False,-999999,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1560357,493630,116,99978669094876,3,30.0,QT2T,3,498,15,69,9,-5,False,-999999,False,-999999,False
1560358,493630,116,99978669094876,4,36.0,QT2T,2,24,2,13,1,30,False,-999999,False,-999999,False
1560369,493634,92,99979428563268,1,0.0,QT2T,1,101,5,25,2,-13,False,-999999,False,-999999,False
1560370,493634,92,99979428563268,2,2.0,QT2T,2,56,4,16,2,-24,False,-999999,False,-999999,False
1560371,493634,92,99979428563268,3,14.0,QT2T,3,303,11,50,3,-7,False,-999999,False,-999999,False

In [118]:
df_BLUE

,group_data_nb,group_size,group_time,sub_num,sub_time,sub_type,sub_channel,sub_Q,sub_width,sub_max_amp,sub_max_pos,sub_baseline,sub_sat,sub_q1,sub_q1_sat,sub_q2,sub_q2_sat
15,5,92,58496262252556,1,0.0,QT2T,5,78,5,20,2,-21,False,-999999,False,-999999,False
16,5,92,58496262252556,2,0.0,QT2T,6,117,6,26,2,-12,False,-999999,False,-999999,False
17,5,92,58496262252556,3,6.0,QT2T,7,349,9,67,3,5,False,-999999,False,-999999,False
45,15,92,58496553110686,1,0.0,QT2T,5,2228,19,336,4,-20,False,-999999,False,-999999,False
46,15,92,58496553110686,2,2.0,QT2T,6,557,14,73,5,-5,False,-999999,False,-999999,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1560282,493607,140,99975286427746,4,12.0,QT2T,5,22,2,12,0,66,False,-999999,False,-999999,False
1560283,493607,140,99975286427746,5,22.0,QT2T,5,22,2,11,1,109,False,-999999,False,-999999,False
1560297,493612,92,99976009220158,1,0.0,QT2T,6,16308,49,2172,4,22,True,-999999,False,-999999,False
1560298,493612,92,99976009220158,2,4.0,QT2T,5,67,5,16,3,41,False,-999999,False,-999999,False
1560299,493612,92,99976009220158,3,18.0,QT2T,7,42,3,15,1,31,False,-999999,False,-999999,False

In [119]:
df_YELLOW

,group_data_nb,group_size,group_time,sub_num,sub_time,sub_type,sub_channel,sub_Q,sub_width,sub_max_amp,sub_max_pos,sub_baseline,sub_sat,sub_q1,sub_q1_sat,sub_q2,sub_q2_sat
0,0,92,58495723952418,1,0.0,QT2T,11,193,8,39,2,20,False,-999999,False,-999999,False
1,0,92,58495723952418,2,4.0,QT2T,10,56,4,16,2,15,False,-999999,False,-999999,False
2,0,92,58495723952418,3,6.0,QT2T,9,123,9,17,2,19,False,-999999,False,-999999,False
9,3,92,58496053429288,1,0.0,QT2T,11,452,14,55,7,16,False,-999999,False,-999999,False
10,3,92,58496053429288,2,2.0,QT2T,10,169,10,26,6,3,False,-999999,False,-999999,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1560361,493631,92,99978876872936,3,4.0,QT2T,10,328,13,33,4,1,False,-999999,False,-999999,False
1560362,493632,116,99978962612506,1,0.0,QT2T,11,129,6,29,2,12,False,-999999,False,-999999,False
1560363,493632,116,99978962612506,2,2.0,QT2T,9,146,6,33,2,1,False,-999999,False,-999999,False
1560364,493632,116,99978962612506,3,4.0,QT2T,10,45,3,16,1,4,False,-999999,False,-999999,False
1560365,493632,116,99978962612506,4,18.0,QT2T,9,190,8,36,3,171,False,-999999,False,-999999,False

In [120]:
df_WHITE

,group_data_nb,group_size,group_time,sub_num,sub_time,sub_type,sub_channel,sub_Q,sub_width,sub_max_amp,sub_max_pos,sub_baseline,sub_sat,sub_q1,sub_q1_sat,sub_q2,sub_q2_sat
6,2,92,58495837196318,1,0.0,QT2T,13,5676,27,849,4,4,False,-999999,False,-999999,False
8,2,92,58495837196318,3,14.0,QT2T,14,82,5,20,2,11,False,-999999,False,-999999,False
21,7,92,58496539511158,1,0.0,QT2T,13,89,5,22,2,-15,False,-999999,False,-999999,False
22,7,92,58496539511158,2,0.0,QT2T,14,80,5,19,2,-26,False,-999999,False,-999999,False
25,8,92,58496540412290,2,6.0,QT2T,13,120,6,26,2,10,False,-999999,False,-999999,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1560342,493626,116,99978316130118,1,0.0,QT2T,13,229,13,31,3,-2,False,-999999,False,-999999,False
1560344,493626,116,99978316130118,3,8.0,QT2T,14,172,7,33,3,15,False,-999999,False,-999999,False
1560345,493626,116,99978316130118,4,38.0,QT2T,13,36,3,13,2,208,False,-999999,False,-999999,False
1560366,493633,92,99979349419924,1,0.0,QT2T,13,146,7,30,2,-13,False,-999999,False,-999999,False
1560367,493633,92,99979349419924,2,2.0,QT2T,14,107,6,23,2,21,False,-999999,False,-999999,False